// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create.sql

package services

import (
	"context"
)

const createTodo = `-- name: CreateTodo :exec
INSERT INTO
    todos (content)
VALUES
    ($1) RETURNING id
`

func (q *Queries) CreateTodo(ctx context.Context, content string) error {
	_, err := q.db.ExecContext(ctx, createTodo, content)
	return err
}
