// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delete.sql

package services

import (
	"context"

	"github.com/google/uuid"
)

const deleteTodo = `-- name: DeleteTodo :exec
DELETE FROM
    todos
WHERE
    id = $1
`

func (q *Queries) DeleteTodo(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTodo, id)
	return err
}
