// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_all.sql

package services

import (
	"context"
)

const getAllTodo = `-- name: GetAllTodo :exec
SELECT
    id, content, completed, created_at, updated_at
FROM
    todos
ORDER BY
    created_at DESC
`

func (q *Queries) GetAllTodo(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, getAllTodo)
	return err
}
