// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package services

import (
	"database/sql"

	"github.com/google/uuid"
)

type Todo struct {
	ID        uuid.UUID    `json:"id"`
	Content   string       `json:"content"`
	Completed sql.NullBool `json:"completed"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}
