// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: update.sql

package services

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const updateTodo = `-- name: UpdateTodo :exec
UPDATE
    todos
SET
    completed = $2
WHERE
    id = $1
`

type UpdateTodoParams struct {
	ID        uuid.UUID    `json:"id"`
	Completed sql.NullBool `json:"completed"`
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) error {
	_, err := q.db.ExecContext(ctx, updateTodo, arg.ID, arg.Completed)
	return err
}
